// Builds src/server/geoip-data.ts (a compact IP-range → country table) from the CC0 "geo-whois-asn-country" CSV files
// (npm: @ip-location-db/geo-whois-asn-country; data from the registries' public WHOIS and ASN records, no licence key).
// Usage: node scripts/build-geoip.mjs <ipv4.csv> <ipv6.csv>
import { readFileSync, writeFileSync } from "node:fs";
import { gzipSync } from "node:zlib";
const [v4Path, v6Path] = process.argv.slice(2);
if (!v4Path || !v6Path) { console.error("Usage: node scripts/build-geoip.mjs ipv4.csv ipv6.csv"); process.exit(1); }
const countries = []; const idx = (cc) => { let i = countries.indexOf(cc); if (i < 0) { i = countries.length; countries.push(cc); } return i; };
const v4 = (s) => s.split(".").reduce((a, o) => a * 256 + Number(o), 0);
function v6top(s) { // the first 64 bits as a BigInt
  let [head, tail = ""] = s.split("::"); const h = head ? head.split(":") : [], t = tail ? tail.split(":") : []; const parts = [...h, ...Array(Math.max(0, 8 - h.length - t.length)).fill("0"), ...t];
  return parts.slice(0, 4).reduce((a, p) => (a << 16n) | BigInt(parseInt(p || "0", 16)), 0n);
}
function merge(rows) { rows.sort((a, b) => (a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0)); const out = []; for (const r of rows) { const l = out[out.length - 1]; if (l && l[2] === r[2] && r[0] <= l[1] + (typeof r[0] === "bigint" ? 1n : 1)) { if (r[1] > l[1]) l[1] = r[1]; } else out.push([...r]); } return out; }
const rows4 = readFileSync(v4Path, "utf8").trim().split("\n").map((l) => { const [a, b, c] = l.split(","); return [v4(a), v4(b), idx(c)]; });
const rows6 = readFileSync(v6Path, "utf8").trim().split("\n").map((l) => { const [a, b, c] = l.split(","); return [v6top(a), v6top(b), idx(c)]; });
const m4 = merge(rows4), m6 = merge(rows6);
const b4 = Buffer.alloc(m4.length * 9); m4.forEach(([s, e, c], i) => { b4.writeUInt32BE(s, i * 9); b4.writeUInt32BE(e, i * 9 + 4); b4[i * 9 + 8] = c; });
const b6 = Buffer.alloc(m6.length * 17); m6.forEach(([s, e, c], i) => { b6.writeBigUInt64BE(s, i * 17); b6.writeBigUInt64BE(e, i * 17 + 8); b6[i * 17 + 16] = c; });
const enc = (b) => gzipSync(b, { level: 9 }).toString("base64");
writeFileSync(new URL("../src/server/geoip-data.ts", import.meta.url), `// Generated by scripts/build-geoip.mjs from CC0 registry data. Do not edit.\nexport const COUNTRIES = ${JSON.stringify(countries)};\nexport const V4 = "${enc(b4)}";\nexport const V6 = "${enc(b6)}";\n`);
console.log("ranges", m4.length, m6.length, "countries", countries.length);
